- name: Execute CLI commands or scripts
  hosts: 
  gather_facts: no
  tasks:
    - name: Run the command
      shell: "ls"
      register: command_output
    - name: "Display the output"
      debug:
        msg: 
        - "{{ command_output.stdout_lines|default([]) + command_output.stderr_lines|default([]) }}"
      when: (command_output.rc == 0)
