- name: Execute CLI commands or scripts
  hosts: pi
  gather_facts: no
  tasks:
    - name: Check system info
      shell: "ls -lh"
      register: command_output
    - name: "Display the output"
      debug:
        msg:  "{{ command_output.stdout_lines }}"
