- name: Execute CLI commands or scripts
  hosts: pi
  gather_facts: no
  tasks:
    - name: Check system info
      shell: 
         echo "This will go in log hile" >/tmp/lo_file.txt
      register: command_output
    - name: "Display the output"
      debug:
        msg:  "{{ command_output.stdout_lines }}"
