
all:
   children:
       cnfs:
          children:
             vdus:
                hosts:
#                   pocvdu3:
#                   vdu0:
#                   vdu1:
                   vdu2:
#                   vdu3:
#                   vdu4:
#                   vdu6:
#                   nrovdu1:
#                   ...
             vcus:
                hosts:
#                   pocvcu01:
#                   vcuCP1:
#                   vcuUP1:
#                   vcuCP2:
#                   vcuUP2:
#                   ...
       enm:
          hosts:
             141.137.238.24:
                ansible_user: shijian_test
                ansible_port: 22
             10.123.41.39:                
                ansible_user: exuzhig     
                ansible_port: 22 
       kdump_nodes:
          hosts:
             vdu0:
       provision_nodes:
          hosts:
#             provisioner1:
             provisioner2:
#             nroprovisioner:
       local:
           hosts:
               local_host:

