all:
   hosts:
      pi:
         ansible_host: 10.0.0.102
         ansible_user: clickitmaster
         ansible_password: PhatM1nh
         ansible_port: 22
      local:
         hosts:
            local_host:
